#!/usr/bin/env bash

if [ -z "${BASH_VERSION:-}" ]; then
  echo 'Error: this script must be run with bash.' >&2
  exit 1
fi

F=$(readlink -f "$0")
cd "$(dirname "$F")"
repo_dir=$(pwd)

set -x

#
# place symlinks to /usr/local/bin
# will not overwrite existing ones
#

if [ "$EUID" -ne 0 ]
  then echo "Please run as root"
  exit
fi

mkdir -p /usr/local/bin
for file in bin/*
do
  ln -s "$repo_dir/$file" /usr/local/bin
done
