#!/usr/bin/env bash

if [ -z "${BASH_VERSION:-}" ]; then
  echo 'Error: this script must be run with bash.' >&2
  exit 1
fi

F=$(readlink -f "$0")
cd "$(dirname "$F")"
repo_dir=$(pwd)

set -x

#
# place symlinks to ~/bin
# will not overwrite existing ones
#

mkdir -p ~/bin
for file in bin/*
do
  ln -s "$repo_dir/$file" ~/bin
done
ln -s "$repo_dir/php-tools" ~/bin
