#!/bin/sh

# bold+cyan+on_orange
highlight=$(tput setab 3)$(tput bold)$(tput setaf 4)
normal=$(tput sgr0)

if ! [ -x "$(command -v git)" ]; then
  echo 'Error: git is not installed.' >&2
  exit 1
fi	
if ! [ -x "$(command -v wget)" ]; then
  echo 'Error: wget is not installed.' >&2
  exit 1
fi	
#if ! [ -x "$(command -v composer)" ]; then
#  echo 'Installing composer' >&2
#  ./install composer
#  exit 1
#fi	

if [ ! -f bin/composer ]; then
   sh ./scripts/composer.install
fi

mkdir -p bin tools installed

if [ $# -eq 0 ]; then
    echo 'specify "all" or choose a specific package to install / re-install'
    echo
    for file in scripts/*.install
    do
        what=$(echo $file | sed "s/scripts.//" | sed "s/.install$//")
        if [ -f installed/$what ]; then
            echo "- $highlight $what $normal - already installed"
        else
            echo "- $highlight $what $normal"
        fi
    done
    exit 1
fi

what=$1

if [ "$1" == "all" ]; then
    for file in scripts/*.install
    do
        what=$(echo $file | sed "s/scripts.//" | sed "s/.install$//")
        if [ -f installed/$what ]; then
            echo "*** already installed: $what"
        else
            echo
            ./install $what
        fi
    done
    exit
fi

if [ ! -f scripts/$what.install ]; then
    echo "unknown package '$what'"
    exit 1
fi

echo "*** installing $highlight $what $normal"
sh -x scripts/$what.install
date > installed/$what
