#!/usr/bin/env bash

if [ -z "${BASH_VERSION:-}" ]; then
  echo 'Error: this script must be run with bash.' >&2
  exit 1
fi

F=$(readlink -f "$0")
cd "$(dirname "$F")"
repo_dir=$(dirname "$F")

# bold+cyan+on_orange
highlight=$(tput setab 3)$(tput bold)$(tput setaf 4)
normal=$(tput sgr0)

if ! [ -x "$(command -v git)" ]; then
  echo 'Error: git is not installed.' >&2
  exit 1
fi	
if ! [ -x "$(command -v wget)" ]; then
  echo 'Error: wget is not installed.' >&2
  exit 1
fi	
#if ! [ -x "$(command -v composer)" ]; then
#  echo 'Installing composer' >&2
#  ./install composer
#  exit 1
#fi	

if [ ! -w . ]; then
   echo Error: Write Permission Denied
   echo "Option 1: run from root: ${highlight}sudo \"$0\" $* ${normal}"
   echo "Option 2: change file ownership: ${highlight}sudo chown -R ${USER:-$LOGNAME} \"$repo_dir\" ${normal}, then run install command again"
   exit 1
fi

mkdir -p bin tools installed

if [ ! -f bin/composer ]; then
   bash ./scripts/composer.install
fi

if [ $# -eq 0 ]; then
    echo 'specify "all" or choose a specific package to install / re-install'
    echo
    for file in scripts/*.install
    do
        what=${file#scripts/}
        what=${what%.install}
        if [ -f "installed/$what" ]; then
            echo "- $highlight $what $normal - already installed"
        else
            echo "- $highlight $what $normal"
        fi
    done
    exit 1
fi

what=$1

if [ "$1" == "all" ]; then
    for file in scripts/*.install
    do
        what=${file#scripts/}
        what=${what%.install}
        if [ -f "installed/$what" ]; then
            echo "*** already installed: $what"
        else
            echo
            ./install "$what"
        fi
    done
    exit
fi

if [ ! -f "scripts/$what.install" ]; then
    echo "unknown package '$what'"
    exit 1
fi

echo "*** installing $highlight $what $normal"
bash -x "scripts/$what.install"
date > "installed/$what"
