#!/bin/sh

F=$(readlink -f "$0")
cd "$(dirname "$F")"

mkdir -p installed

# bold+cyan+on_orange
highlight=$(tput setab 3)$(tput bold)$(tput setaf 4)
normal=$(tput sgr0)

if [ $# -eq 0 ]; then
    echo 'specify "all" or specific package to update:'
    echo
    echo installed packages:
    ls installed | sed "s/^/+ /"
    exit 1
fi

if [ ! -w . ]; then
   echo Error: Write Permission Denied
   echo Option 1: run from root: $highlight sudo $0 $* $normal
   echo Option 2: change file ownership: $highlight sudo chown -R $USER $(dirname "$F") $normal, then run update command again
   exit 1
fi


what=$1

if [ "$1" == "all" ]; then
    for file in installed/*
    do
        what=$(echo $file | sed "s/^installed.//" )
        ./update $what
    done
    exit
fi

if [ ! -f scripts/$what.install ]; then
    echo "unknown package '$what'"
    exit 1
fi

if [ -f scripts/$what.update ]; then
  echo "*** updating $highlight $what $normal"
  sh -x scripts/$what.update
else
  echo "*** re-installing $highlight $what $normal"
  sh -x scripts/$what.install
fi
date > installed/$what
